MarketPlace.Web/Areas/Seller/Controllers/ProductDiscountController.cs
using MarketPlace.Application.Services.Interfaces;
using MarketPlace.DataLayer.DTOs.ProductDiscount;
using MarketPlace.Web.PresentationExtensions;
using Microsoft.AspNetCore.Mvc;

namespace MarketPlace.Web.Areas.Seller.Controllers;

public class ProductDiscountController : SellerBaseController
{
    #region constructor

    private readonly IProductDiscountService _productDiscountService;
    private readonly ISellerService _sellerService;

    public ProductDiscountController(IProductDiscountService productDiscountService, ISellerService sellerService)
    {
        _productDiscountService = productDiscountService;
        _sellerService = sellerService;
    }

    #endregion

    #region filter

    [HttpGet("discounts")]
    [HttpGet("discounts/{ProductId}")]
    public async Task<IActionResult> FilterDiscounts(FilterProductDiscountDTO filter)
    {
        // if (filter.ProductId == null || filter.ProductId == 0) return NotFound();
        var seller = await _sellerService.GetLastActiveSellerByUserId(User.GetUserId());
        filter.SellerId = seller.Id;
        return View(await _productDiscountService.FilterProductDiscountDTO(filter));
    }

    #endregion

    #region create discount

    [HttpGet("create-discount")]
    public IActionResult CreateDiscount()
    {
        return View();
    }

    [HttpPost("create-discount"), ValidateAntiForgeryToken]
    public async Task<IActionResult> CreateDiscount(CreateProductDiscountDTO discount)
    {
        if (ModelState.IsValid)
        {
            var seller = await _sellerService.GetLastActiveSellerByUserId(User.GetUserId());
            var res = await _productDiscountService.CreateProductDiscount(discount, seller.Id);

            switch (res)
            {
                case CreateDiscountResult.Error:
                    TempData[ErrorMessage] = "عملیات ثبت تخفیف مورد نظر با شکست مواجه شد";
                    break;
                case CreateDiscountResult.ProductNotFound:
                    TempData[WarningMessage] = "محصول مورد نظر یافت نشد";
                    break;
                case CreateDiscountResult.ProductIsNotForSeller:
                    TempData[WarningMessage] = "محصول مورد نظر یافت نشد";
                    break;
                case CreateDiscountResult.Success:
                    TempData[SuccessMessage] = "عملیات ثبت تخفیف برای محصول مورد نظر با موفقیت انجام شد";
                    return RedirectToAction("FilterDiscounts");
            }
        }
        return View(discount);
    }

    #endregion
}

MarketPlace.Web/Areas/Seller/Views/ProductDiscount/CreateDiscount.cshtml
@using MarketPlace.DataLayer.DTOs.ProductDiscount;
@model CreateProductDiscountDTO;

@{
    ViewData["Title"] = "ثبت تخفیف جدید";
}

@section styles
{
    <link rel="stylesheet" href="/lib/EasyAutocomplete/easy-autocomplete.min.css" />
    <link rel="stylesheet" href="/lib/EasyAutocomplete/easy-autocomplete.themes.min.css" />
}

@section scripts
    {
    <partial name="_JqueryValidators" />
    <script src="/lib/EasyAutocomplete/jquery.easy-autocomplete.min.js"></script>
    <script>
        var options = {
            url: function (phrase) {
                return "/seller/products-autocomplete?productName=" + phrase;
            },

            getValue: function (element) {
                return element.title;
            },

            list: {
                match: {
                    enabled: true
                },

                onSelectItemEvent: function () {
                    var value = $("#ProductName").getSelectedItemData().id;

                    $("#ProductId").val(value).trigger("change");
                }
            },
            theme: "square"
        };

        $("#ProductName").easyAutocomplete(options);

        $("#ExpireDate").persianDatepicker({
            months: ["فروردین", "اردیبهشت", "خرداد", "تیر", "مرداد", "شهریور", "مهر", "آبان", "آذر", "دی", "بهمن", "اسفند"],
            dowTitle: ["شنبه", "یکشنبه", "دوشنبه", "سه شنبه", "چهارشنبه", "پنج شنبه", "جمعه"],
            shortDowTitle: ["ش", "ی", "د", "س", "چ", "پ", "ج"],
            showGregorianDate: !1,
            persianNumbers: !0,
            formatDate: "YYYY/MM/DD",
            selectedBefore: !1,
            selectedDate: null,
            startDate: null,
            endDate: null,
            prevArrow: '\u25c4',
            nextArrow: '\u25ba',
            theme: 'default',
            alwaysShow: !1,
            selectableYears: null,
            selectableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            cellWidth: 25, // by px
            cellHeight: 20, // by px
            fontSize: 13, // by px
            isRTL: !1,
            calendarPosition: {
                x: 0,
                y: 0,
            },
            onShow: function () { },
            onHide: function () { },
            onSelect: function () { },
            onRender: function () { }
        });
    </script>
}

<div class="breadcrumbs_area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="breadcrumb_content">
                    <ul>
                        <li><a href="/">خانه</a></li>
                        <li>@ViewData["Title"]</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<section class="main_content_area">
    <div class="container">
        <div class="account_dashboard">
            <div class="row">
                <div class="col-sm-12 col-md-3 col-lg-3">
                    @await Component.InvokeAsync("SellerSidebar")
                </div>
                <div class="col-sm-12 col-md-9 col-lg-9">
                    <!-- Tab panes -->
                    <div class="tab-content dashboard_content">
                        <div class="tab-pane fade active show" id="account-details">
                            <h3>@ViewData["Title"]</h3>
                            <div class="login">
                                <div class="login_form_container">
                                    <div class="account_login_form">
                                        <form asp-area="Seller" asp-controller="ProductDiscount" asp-action="CreateDiscount">
                                            <input type="hidden" asp-for="ProductId" />

                                            <label>محصول مورد نظر</label>
                                            <input type="text" id="ProductName">
                                            <br />

                                            <label>تاریخ انقضا</label>
                                            <input asp-for="ExpireDate" style="width: 100%">
                                            <span class="text-danger" asp-validation-for="ExpireDate"></span>
                                            <br />

                                            <label>تعداد تخفیف</label>
                                            <input asp-for="DiscountNumber">
                                            <span class="text-danger" asp-validation-for="DiscountNumber"></span>
                                            <br />

                                            <label>درصد تخفیف</label>
                                            <input asp-for="Percentage" type="text">
                                            <span class="text-danger" asp-validation-for="Percentage"></span>
                                            <br />

                                            <div class="save_button primary_btn default_button">
                                                <button type="submit">ذخیره</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

MarketPlace.Web/Areas/Seller/Views/ProductDiscount/FilterDiscounts.cshtml
@using MarketPlace.Application.Utils;
@using MarketPlace.DataLayer.DTOs.ProductDiscount;
@model FilterProductDiscountDTO;

@{
    ViewData["Title"] = "فیلتر کد های تخفیف";
}

<div class="breadcrumbs_area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="breadcrumb_content">
                    <ul>
                        <li><a href="/">خانه</a></li>
                        <li>@ViewData["Title"]</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>


<section class="main_content_area">
    <div class="container">
        <div class="account_dashboard">
            <div class="row">
                <div class="col-sm-12 col-md-3 col-lg-3">
                    @await Component.InvokeAsync("SellerSidebar")
                </div>
                <div class="col-sm-12 col-md-9 col-lg-9">
                    <!-- Tab panes -->
                    <div class="tab-content dashboard_content">
                        <div class="tab-pane fade active show" id="account-details">
                            <h3>
                                @ViewData["Title"]
                                <a class="btn btn-outline-primary" asp-area="Seller" asp-controller="ProductDiscount" asp-action="CreateDiscount">ثبت تخفیف جدید</a>
                            </h3>
                            <form method="get" asp-area="Seller" asp-controller="SellerWallet" asp-action="Index" id="filter-form">
                                <input type="hidden" asp-for="PageId" />
                                <div class="table-responsive">
                                    @if (Model.ProductDiscounts != null && Model.ProductDiscounts.Any())
                                    {
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>شناسه</th>
                                                    <th>مقدار</th>
                                                    <th>تعداد</th>
                                                    <th>تاریخ انقضا</th>
                                                    <th>دستورات</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var discount in Model.ProductDiscounts)
                                                {
                                                    <tr>
                                                        <td>@discount.Id</td>
                                                        <td>@discount.Percentage %</td>
                                                        <td>@discount.DiscountNumber</td>
                                                        <td>@discount.ExpireDate.ToShamsiDate()</td>
                                                        <td></td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                        <partial name="_PagingPartial" model="@Model.GetCurrentPaging()" />
                                    }
                                    else
                                    {
                                        <partial name="_NoItemFound" />
                                    }
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>